from rbc_meta.utils_next.reflect import reflect
from rbc_meta.utils_next.builtin import size_t, u64, u32


@reflect(
    pybind=True,
    cpp_prefix="RBC_WORLD_API",
    cpp_namespace="rbc",
    module_name="resource_loader",
)
class AsyncResourceLoader:
    def initialize(self, num_threads: int): ...
    def shutdown(self): ...
    def set_cache_budget(self, bytes: size_t): ...
    def get_cache_budget(self) -> size_t: ...
    def get_memory_usage(self) -> size_t: ...
    def load_resource(
        self, resource_id: u64, type_value: u32, path: str, options_json: str
    ) -> bool: ...
    def is_loaded(resource_id: u64) -> bool: ...
    def unload_resource(self, resource_id: u64): ...
