from rbc_meta.utils.reflect import reflect
from rbc_meta.utils.builtin import DataBuffer
from rbc_meta.utils.builtin import (
    uint,
    uint2,
    uint3,
    uint4,
    ulong,
    float3,
    float4x4,
    VoidPtr,
    GUID,
    double,
    float2,
    double3,
    float4,
    double4x4,
    Vector,
    RC,
    RCBase,
    Ref,
    Const,
    long,
)
from rbc_meta.types.resource import LCPixelStorage
from enum import Enum


class LCPYBuffer:
    __slot__ = {}
    _reflected_ = True
    _cpp_type_name = "luisa::compute::BufferCreationInfoInterop"


class LCPYBufferInfo:
    __slot__ = {}
    _reflected_ = True
    _cpp_type_name = "luisa::compute::BufferCreationInfoInterop"
    _py_type_name = "luisa.lcapi.BufferCreationInfo"


class Callback:
    __slot__ = {}
    _reflected_ = True

    def _cpp_type_name(py_interface: bool, is_view: bool):
        if py_interface:
            return "py::function"
        else:
            return "luisa::move_only_function<void(rbc::RCBase*)>&&"

    _py_type_name = ""
    _cpp_arg_call = "to_cppfunc_5d4636ab<rbc::RCBase*>"


class LCPYImage2D:
    __slot__ = {}
    _cpp_type_name = "luisa::compute::TextureCreationInfo"


class LCPYImage2DInfo:
    __slot__ = {}
    _cpp_type_name = "luisa::compute::TextureCreationInfo"
    _py_type_name = "luisa.lcapi.TextureCreationInfo"


@reflect(cpp_namespace="rbc", module_name="world_interface", pybind=True)
class BasicDataType(Enum):
    INT = 0
    DOUBLE = 1
    STRING = 2
    BOOL = 3
    NONE = 4


@reflect(cpp_namespace="rbc", pybind=True)
class ResourceLoadStatus(Enum):
    Unloaded = 0
    Loading = 1
    Loaded = 2
    Installing = 3
    Installed = 4


@reflect(cpp_namespace="rbc", pybind=True)
class RendererGeometryType(Enum):
    NONE = 0
    Depth = 1 << 0  # float: Distance to camera
    Normal = 1 << 1  # packed float3: normal-xyz
    # packed uint4:  X: object id  Y: primitive id ZW: triangle bary-centric (float2)
    ObjectID = 1 << 2
    PrimID = 1 << 3
    Barycentric = 1 << 4

    Emission = 1 << 5  # packed float3: emission color (sampled from spectrum)
    Albedo = 1 << 6  # packed float3: albedo color (sampled from spectrum)
    MaterialID = 1 << 7


# After change RendererGeometryType, make sure "geometry_byte_size" in "rbc\render_plugin\src\offline_pt_pass.cpp" also updated!


@reflect(cpp_namespace="rbc", pybind=True)
class BaseObjectType(Enum):
    NONE = 0
    Component = 1
    Entity = 2
    Resource = 3
    Custom = 4


@reflect(
    pybind=True,
    cpp_prefix="TEST_GRAPHICS_API",
    cpp_namespace="rbc",
    create_instance=False,
)
class Object:
    def guid() -> GUID: ...
    def type_name() -> str: ...
    def type_id() -> GUID: ...
    def is_type(name: str) -> bool: ...
    def base_type() -> BaseObjectType: ...


@reflect(
    pybind=True,
    cpp_prefix="TEST_GRAPHICS_API",
    cpp_namespace="rbc",
    create_instance=False,
)
class Entity(Object):
    def add_component(name: str) -> VoidPtr: ...
    def get_component(name: str) -> VoidPtr: ...
    def remove_component(name: str) -> bool: ...
    def name() -> str: ...
    def set_name(name: str) -> None: ...
    def dispose() -> None: ...


@reflect(
    pybind=True,
    cpp_prefix="TEST_GRAPHICS_API",
    cpp_namespace="rbc",
    create_instance=False,
)
class Component(Object):
    def entity() -> Entity: ...
    def update_data() -> None: ...
    def dispose() -> None: ...


@reflect(
    pybind=True,
    cpp_prefix="TEST_GRAPHICS_API",
    cpp_namespace="rbc",
    create_instance=False,
)
class TransformComponent(Component):
    def position() -> double3: ...
    def scale() -> double3: ...
    def rotation() -> float4: ...
    def trs() -> double4x4: ...
    def trs_float() -> float4x4: ...
    def children_count() -> ulong: ...
    def remove_children(children: VoidPtr) -> bool: ...
    def set_pos(pos: double3, recursive: bool) -> None: ...
    def set_scale(scale: double3, recursive: bool) -> None: ...
    def set_rotation(rotation: float4, recursive: bool) -> None: ...
    def set_trs_matrix(trs: double4x4, recursive: bool) -> None: ...

    def set_trs(
        pos: double3, rotation: float4, scale: double3, recursive: bool
    ) -> None: ...


@reflect(
    pybind=True,
    cpp_prefix="TEST_GRAPHICS_API",
    cpp_namespace="rbc",
    create_instance=False,
)
class LightComponent(Component):
    def add_area_light(luminance: float3, visible: bool) -> None: ...
    def add_disk_light(luminance: float3, visible: bool) -> None: ...
    def add_point_light(luminance: float3, visible: bool) -> None: ...

    def add_spot_light(
        luminance: float3,
        angle_radians: float,
        small_angle_radians: float,
        angle_atten_pow: float,
        visible: bool,
    ) -> None: ...

    def luminance() -> float3: ...
    def angle_radians() -> float: ...
    def small_angle_radians() -> float: ...
    def angle_atten_pow() -> float: ...


# Resources


@reflect(
    pybind=True,
    cpp_prefix="TEST_GRAPHICS_API",
    cpp_namespace="rbc",
    create_instance=False,
)
class Resource(Object):
    def load_status() -> ResourceLoadStatus: ...
    def load() -> None: ...
    def install() -> bool: ...
    def path() -> str: ...
    def save_to_path() -> bool: ...
    def wait_loading() -> None: ...


@reflect(pybind=True, cpp_prefix="TEST_GRAPHICS_API", cpp_namespace="rbc")
class BasicData:
    def type() -> BasicDataType: ...
    def get_int() -> long: ...
    def get_float() -> double: ...
    def get_string() -> str: ...
    def get_bool() -> bool: ...
    def set_int(v: long) -> None: ...
    def set_float(v: double) -> None: ...
    def set_string(v: str) -> None: ...
    def set_bool(v: bool) -> None: ...
    def get_resource() -> Resource: ...
    def set_resource(res: Resource) -> None: ...


@reflect(pybind=True, cpp_prefix="TEST_GRAPHICS_API", cpp_namespace="rbc")
class TextureResource(Resource):
    def is_vt() -> bool: ...
    def pack_to_tile() -> bool: ...
    def pixel_storage() -> LCPixelStorage: ...
    def size() -> uint2: ...
    def mip_level() -> uint: ...

    def create_empty(
        pixel_storage: LCPixelStorage,
        size: uint2,
        mip_level: uint,
        is_virtual_texture: bool,
    ) -> None: ...
    def load_executed() -> bool: ...
    def has_data_buffer() -> bool: ...
    def data_buffer() -> DataBuffer: ...
    def heap_index() -> uint: ...
    def set_skybox() -> None: ...
    def device_texture() -> LCPYImage2D: ...


@reflect(pybind=True, cpp_prefix="TEST_GRAPHICS_API", cpp_namespace="rbc")
class MeshResource(Resource):
    def vertex_count() -> uint: ...
    def triangle_count() -> uint: ...
    def uv_count() -> uint: ...
    def submesh_count() -> uint: ...
    def is_transforming_mesh() -> bool: ...
    def contained_normal() -> bool: ...
    def data_buffer() -> DataBuffer: ...
    def pos_buffer() -> DataBuffer: ...
    def normal_buffer() -> DataBuffer: ...
    def tangent_buffer() -> DataBuffer: ...
    def uv_buffer(uv_count: uint) -> DataBuffer: ...
    def triangle_indices_buffer() -> DataBuffer: ...
    def contained_tangent() -> bool: ...
    def has_data_buffer() -> bool: ...
    def basic_size_bytes() -> ulong: ...
    def extra_size_bytes() -> ulong: ...
    def desire_size_bytes() -> ulong: ...

    def device_data_buffer() -> LCPYBuffer: ...
    def device_mutable_buffer() -> LCPYBuffer: ...  # for transform-mesh

    def create_empty(
        submesh_offsets: DataBuffer,
        vertex_count: uint,
        triangle_count: uint,
        uv_count: uint,
        contained_normal: bool,
        contained_tangent: bool,
    ) -> None: ...

    def create_as_morphing_instance(origin_mesh: "MeshResource") -> None: ...
    def build_before_tick() -> None: ...


@reflect(pybind=True, cpp_prefix="TEST_GRAPHICS_API", cpp_namespace="rbc")
class BufferResource(Resource):
    def size_bytes() -> ulong: ...
    def buffer() -> LCPYBuffer: ...
    def host_data() -> DataBuffer: ...
    def create_empty(size_bytes: ulong, create_device_buffer: bool) -> None: ...


@reflect(pybind=True, cpp_prefix="TEST_GRAPHICS_API", cpp_namespace="rbc")
class MaterialResource(Resource):
    def mat_code() -> uint: ...
    def load_from_json(json: str) -> None: ...
    def dump_json() -> str: ...


# @reflect(
#     pybind=True,
#     cpp_prefix="TEST_GRAPHICS_API",
#     cpp_namespace="rbc"
# )
# class GaussianSplatResource(Resource):
#     def empty() -> bool: ...
#     def num_gaussians() -> uint: ...
#     def sh_degree() -> uint: ...
#     def host_data_size_bytes() -> ulong: ...
#     def data_size_bytes() -> ulong: ...
#     def create_empty(num_gaussians: uint, sh_degree: uint) -> None: ...
#     def is_procedural_dirty() -> bool: ...
#     def procedural_instance_id() -> uint: ...


@reflect(pybind=True, cpp_prefix="TEST_GRAPHICS_API", cpp_namespace="rbc")
class VoxelResource(Resource):
    """Resource class for AABB-based Voxel data.

    Stores axis-aligned bounding boxes for GPU-accelerated voxel rendering.
    """

    def empty() -> bool: ...
    def num_voxels() -> uint: ...
    def host_data_size_bytes() -> ulong: ...
    def create_empty(num_voxels: uint) -> None: ...
    def is_procedural_dirty() -> bool: ...
    def procedural_instance_id() -> uint: ...


@reflect(pybind=True, cpp_prefix="TEST_GRAPHICS_API", cpp_namespace="rbc")
class SDFVoxelResource(Resource):
    """Resource class for SDF (Signed Distance Field) Voxel data.

    Stores 3D signed distance field data for GPU-accelerated rendering and ray marching.
    """

    def empty() -> bool: ...
    def grid_size() -> uint3: ...
    def num_voxels() -> ulong: ...
    def host_data_size_bytes() -> ulong: ...
    def uvw_scale() -> float3: ...
    def uvw_offset() -> float3: ...
    def sample_count() -> uint: ...
    def set_uvw_scale(scale: float3) -> None: ...
    def set_uvw_offset(offset: float3) -> None: ...
    def set_sample_count(count: uint) -> None: ...
    def create_empty(grid_size: uint3) -> None: ...
    def is_procedural_dirty() -> bool: ...
    def procedural_instance_id() -> uint: ...


@reflect(
    pybind=True,
    cpp_prefix="TEST_GRAPHICS_API",
    cpp_namespace="rbc",
    create_instance=False,
)
class RenderComponent(Component):
    def get_tlas_index() -> uint: ...
    def remove_object() -> None: ...

    def update_object(
        mat_vector: Ref[Const[Vector[RC[RCBase]]]], mesh: MeshResource
    ) -> None: ...

    def update_mesh(mesh: MeshResource) -> None: ...
    def update_material(mat_vector: Ref[Const[Vector[RC[RCBase]]]]) -> None: ...

    def mesh() -> MeshResource: ...
    def mat_count() -> ulong: ...
    def get_material(idx: ulong) -> MaterialResource: ...


@reflect(pybind=True, cpp_prefix="TEST_GRAPHICS_API", cpp_namespace="rbc")
class RenderSettings:
    # ========== SkySettings ==========
    def get_sky_angle() -> float: ...
    def set_sky_angle(value: float) -> None: ...
    def get_sky_max_lum() -> float: ...
    def set_sky_max_lum(value: float) -> None: ...
    def get_sky_color() -> float3: ...
    def set_sky_color(value: float3) -> None: ...
    def get_sun_color() -> float3: ...
    def set_sun_color(value: float3) -> None: ...
    def get_sun_dir() -> float3: ...
    def set_sun_dir(value: float3) -> None: ...
    def get_sun_intensity() -> float: ...
    def set_sun_intensity(value: float) -> None: ...
    def get_sun_angle() -> float: ...
    def set_sun_angle(value: float) -> None: ...

    # ========== DisplaySettings ==========
    def get_use_linear_sdr() -> bool: ...
    def set_use_linear_sdr(value: bool) -> None: ...
    def get_use_hdr_display() -> bool: ...
    def set_use_hdr_display(value: bool) -> None: ...
    def get_use_hdr_10() -> bool: ...
    def set_use_hdr_10(value: bool) -> None: ...
    def get_gamma() -> float: ...
    def set_gamma(value: float) -> None: ...
    def get_chromatic_aberration() -> float: ...
    def set_chromatic_aberration(value: float) -> None: ...

    # ========== ExposureSettings ==========
    def get_use_auto_exposure() -> bool: ...
    def set_use_auto_exposure(value: bool) -> None: ...
    def get_filtering() -> float2: ...
    def set_filtering(value: float2) -> None: ...
    def get_min_luminance() -> float: ...
    def set_min_luminance(value: float) -> None: ...
    def get_max_luminance() -> float: ...
    def set_max_luminance(value: float) -> None: ...
    def get_global_exposure() -> float: ...
    def set_global_exposure(value: float) -> None: ...

    # ========== PathTracerSettings ==========
    def get_offline_spp() -> uint: ...
    def set_offline_spp(value: uint) -> None: ...
    def get_offline_origin_bounce() -> uint: ...
    def set_offline_origin_bounce(value: uint) -> None: ...
    def get_offline_indirect_bounce() -> uint: ...
    def set_offline_indirect_bounce(value: uint) -> None: ...
    def get_denoise() -> bool: ...
    def set_denoise(value: bool) -> None: ...
    def get_enable_ao_mode() -> bool: ...
    def set_enable_ao_mode(value: bool) -> None: ...
    def get_ao_use_cosine_sample() -> bool: ...
    def set_ao_use_cosine_sample(value: bool) -> None: ...
    def get_ao_max_radius() -> float4: ...
    def set_ao_max_radius(value: float4) -> None: ...
    def get_ao_atten_pow() -> float4: ...
    def set_ao_atten_pow(value: float4) -> None: ...

    # ========== DistortionSettings ==========
    def get_distortion_scale() -> float: ...
    def set_distortion_scale(value: float) -> None: ...
    def get_distortion_intensity() -> float: ...
    def set_distortion_intensity(value: float) -> None: ...
    def get_distortion_intensity_multiplier() -> float2: ...
    def set_distortion_intensity_multiplier(value: float2) -> None: ...
    def get_distortion_center() -> float2: ...
    def set_distortion_center(value: float2) -> None: ...

    # ========== ToneMappingSettings - LPM ==========
    def get_lpm_shoulder() -> bool: ...
    def set_lpm_shoulder(value: bool) -> None: ...
    def get_lpm_soft_gap() -> float: ...
    def set_lpm_soft_gap(value: float) -> None: ...
    def get_lpm_hdr_max() -> float: ...
    def set_lpm_hdr_max(value: float) -> None: ...
    def get_lpm_exposure() -> float: ...
    def set_lpm_exposure(value: float) -> None: ...
    def get_lpm_contrast() -> float: ...
    def set_lpm_contrast(value: float) -> None: ...
    def get_lpm_shoulder_contrast() -> float: ...
    def set_lpm_shoulder_contrast(value: float) -> None: ...
    def get_lpm_saturation() -> float3: ...
    def set_lpm_saturation(value: float3) -> None: ...
    def get_lpm_crosstalk() -> float3: ...
    def set_lpm_crosstalk(value: float3) -> None: ...
    def get_lpm_display_min_luminance() -> float: ...
    def set_lpm_display_min_luminance(value: float) -> None: ...
    def get_lpm_display_max_luminance() -> float: ...
    def set_lpm_display_max_luminance(value: float) -> None: ...

    # ========== ToneMappingSettings - ACES ==========
    def get_aces_temperature() -> float: ...
    def set_aces_temperature(value: float) -> None: ...
    def get_aces_tint() -> float: ...
    def set_aces_tint(value: float) -> None: ...
    def get_aces_use_white_balance_mode() -> bool: ...
    def set_aces_use_white_balance_mode(value: bool) -> None: ...
    def get_aces_hue_shift() -> float: ...
    def set_aces_hue_shift(value: float) -> None: ...
    def get_aces_saturation() -> float: ...
    def set_aces_saturation(value: float) -> None: ...
    def get_aces_contrast() -> float: ...
    def set_aces_contrast(value: float) -> None: ...
    def get_aces_mixer_red_out_red_in() -> float: ...
    def set_aces_mixer_red_out_red_in(value: float) -> None: ...
    def get_aces_mixer_red_out_green_in() -> float: ...
    def set_aces_mixer_red_out_green_in(value: float) -> None: ...
    def get_aces_mixer_red_out_blue_in() -> float: ...
    def set_aces_mixer_red_out_blue_in(value: float) -> None: ...
    def get_aces_mixer_green_out_red_in() -> float: ...
    def set_aces_mixer_green_out_red_in(value: float) -> None: ...
    def get_aces_mixer_green_out_green_in() -> float: ...
    def set_aces_mixer_green_out_green_in(value: float) -> None: ...
    def get_aces_mixer_green_out_blue_in() -> float: ...
    def set_aces_mixer_green_out_blue_in(value: float) -> None: ...
    def get_aces_mixer_blue_out_red_in() -> float: ...
    def set_aces_mixer_blue_out_red_in(value: float) -> None: ...
    def get_aces_mixer_blue_out_green_in() -> float: ...
    def set_aces_mixer_blue_out_green_in(value: float) -> None: ...
    def get_aces_mixer_blue_out_blue_in() -> float: ...
    def set_aces_mixer_blue_out_blue_in(value: float) -> None: ...
    def get_aces_lift() -> float4: ...
    def set_aces_lift(value: float4) -> None: ...
    def get_aces_gamma() -> float4: ...
    def set_aces_gamma(value: float4) -> None: ...
    def get_aces_gain() -> float4: ...
    def set_aces_gain(value: float4) -> None: ...
    def get_aces_color_filter() -> float4: ...
    def set_aces_color_filter(value: float4) -> None: ...
    def get_aces_hdr_display_multiplier() -> float: ...
    def set_aces_hdr_display_multiplier(value: float) -> None: ...
    def get_aces_hdr_paper_white() -> float: ...
    def set_aces_hdr_paper_white(value: float) -> None: ...

    def serialize_to_json() -> str: ...
    def deserialize_from_json(json: str) -> None: ...


@reflect(
    pybind=True,
    cpp_prefix="TEST_GRAPHICS_API",
    cpp_namespace="rbc",
    create_instance=False,
)
class CameraComponent(Component):
    def fov() -> double: ...
    def set_fov(value: double) -> None: ...
    def aspect_ratio() -> double: ...
    def set_aspect_ratio(value: double) -> None: ...
    def near_plane() -> double: ...
    def set_near_plane(value: double) -> None: ...
    def far_plane() -> double: ...
    def set_far_plane(value: double) -> None: ...
    def aperture() -> double: ...
    def set_aperture(value: double) -> None: ...
    def enable_physical_camera() -> bool: ...
    def set_enable_physical_camera(value: bool) -> None: ...
    def focus_distance() -> double: ...
    def set_focus_distance(value: double) -> None: ...
    def auto_aspect_ratio() -> bool: ...
    def set_auto_aspect_ratio(value: bool) -> None: ...

    def render_image(self) -> LCPYImage2D: ...
    def config_render_image(size: uint2, storage: LCPixelStorage) -> None: ...
    def release_render_image() -> None: ...
    def set_frame_index(frame_index: ulong) -> None: ...

    def enable_camera() -> None: ...
    def disable_camera() -> None: ...
    def save_image_to(path: str) -> None: ...

    def set_geometry_export_buffer(
        self, buffer: LCPYBufferInfo, channel_type: RendererGeometryType
    ) -> None: ...

    def clear_geometry_export_buffer() -> None: ...
    def render_settings() -> RenderSettings: ...


@reflect(pybind=True, cpp_prefix="TEST_GRAPHICS_API", cpp_namespace="rbc")
class DataComponentEventType(Enum):
    OnAwake = 0
    OnDestroy = 1
    BeforeFrame = 2
    BeforeRender = 3
    AfterFrame = 4
    OnTransformChange = 5


# Import, load and manage project
@reflect(
    pybind=True,
    cpp_prefix="TEST_GRAPHICS_API",
    cpp_namespace="rbc",
    create_instance=False,
)
class DataComponent(Component):
    def get_info(name: str) -> BasicData: ...
    def set_info(name: str, data: BasicData) -> None: ...
    def has_info(name: str) -> bool: ...
    def remove_info(name: str) -> bool: ...
    def info_count() -> ulong: ...
    def clear_infos() -> None: ...

    def bind_event(event_type: DataComponentEventType, callback_name: str) -> None: ...

    def unbind_event(event_type: DataComponentEventType) -> None: ...


@reflect(
    pybind=True,
    cpp_prefix="TEST_GRAPHICS_API",
    cpp_namespace="rbc",
    create_instance=False,
)
class AtmosphereComponent(Component):
    def texture() -> TextureResource: ...
    def update_texture(tex: TextureResource) -> None: ...


@reflect(pybind=True, cpp_prefix="TEST_GRAPHICS_API", cpp_namespace="rbc")
class EntitiesCollection:
    def count() -> ulong: ...
    def get_entity(index: ulong) -> Entity: ...


@reflect(pybind=True, cpp_prefix="TEST_GRAPHICS_API", cpp_namespace="rbc")
class Scene(Resource):
    def get_entity(guid: GUID) -> Entity: ...
    def get_or_add_entity(guid: GUID) -> Entity: ...
    def add_entity() -> Entity: ...
    def update_data() -> None: ...
    def remove_entity(guid: GUID) -> None: ...
    def get_entity_by_name(name: str) -> Entity: ...
    def get_entities_by_name(name: str) -> EntitiesCollection: ...


@reflect(pybind=True, cpp_prefix="TEST_GRAPHICS_API", cpp_namespace="rbc")
class SkeletonResource(Resource):
    # Basic interface
    def ref_skel() -> VoidPtr: ...
    def log_brief() -> None: ...

    # Bone hierarchy details - essential for physics animation
    def get_num_joints() -> int: ...
    def get_num_soa_joints() -> int: ...
    def get_joint_names() -> Vector[str]: ...
    def get_joint_parents() -> Vector[int]: ...
    def get_joint_rest_poses() -> Vector[float4x4]: ...
    def get_parent_index(joint_index: int) -> int: ...


@reflect(pybind=True, cpp_prefix="TEST_GRAPHICS_API", cpp_namespace="rbc")
class SkinResource(Resource):
    def ref_skel() -> SkeletonResource: ...
    def ref_mesh() -> MeshResource: ...
    def generate_LUT() -> None: ...
    def log_brief() -> None: ...
    def JointRemaps() -> Vector[str]: ...
    def InverseBindPoses() -> Vector[float4x4]: ...
    def JointRemapsLUT() -> Vector[uint]: ...


@reflect(
    pybind=True,
    cpp_prefix="TEST_GRAPHICS_API",
    cpp_namespace="rbc",
)
class AnimSequence:
    def get_num_soa_tracks() -> int: ...
    def get_num_tracks() -> int: ...
    def log_brief() -> None: ...

    def get_animation_pose(pose_data: VoidPtr, extract_context: VoidPtr) -> None: ...


@reflect(pybind=True, cpp_prefix="TEST_GRAPHICS_API", cpp_namespace="rbc")
class AnimSequenceResource(Resource):
    def ref_seq() -> AnimSequence: ...
    def ref_skel() -> SkeletonResource: ...
    def log_brief() -> None: ...


@reflect(pybind=True, cpp_prefix="TEST_GRAPHICS_API", cpp_namespace="rbc")
class AnimGraphResource(Resource):
    def create_simple_anim_graph(anim_seq: AnimSequenceResource) -> bool: ...


@reflect(pybind=True, cpp_prefix="TEST_GRAPHICS_API", cpp_namespace="rbc")
class SkelMeshResource(Resource):
    def GetSkinResource() -> SkinResource: ...
    def ref_skin() -> SkinResource: ...
    def ref_skeleton() -> SkeletonResource: ...
    def ref_anim_graph() -> AnimGraphResource: ...


@reflect(
    pybind=True,
    cpp_prefix="TEST_GRAPHICS_API",
    cpp_namespace="rbc",
    create_instance=False,
)
class SkelMeshComponent(Component):
    def SetRefSkelMesh(skel_mesh: SkelMeshResource) -> None: ...
    def tick(delta_time: float) -> None: ...
    def update_render() -> None: ...
    def remove_object() -> None: ...
    def GetRuntimeMesh() -> MeshResource: ...
    def IsEnabled() -> bool: ...


@reflect(pybind=True, cpp_prefix="TEST_GRAPHICS_API", cpp_namespace="rbc")
class FileMeta:
    def guid() -> GUID: ...
    def meta_json() -> str: ...


@reflect(pybind=True, cpp_prefix="TEST_GRAPHICS_API", cpp_namespace="rbc")
class Project:
    def init(assets_root_dir: str) -> None: ...
    def import_scene(path: str, extra_meta: str) -> Scene: ...
    def get_resource(guid: GUID, load_content_async: bool) -> Resource: ...
    def scan_project() -> None: ...
    def get_file_meta(type_id: GUID, dest_path: str) -> FileMeta: ...
    def import_mesh(path: str) -> MeshResource: ...
    def import_texture(path: str, mip_level: uint, to_vt: bool) -> TextureResource: ...
    def import_material(path: str) -> MaterialResource: ...
    def import_skeleton(path: str) -> SkeletonResource: ...
    def import_skin(path: str) -> SkinResource: ...
    def import_anim_sequence(path: str) -> AnimSequenceResource: ...


@reflect(pybind=True, cpp_prefix="TEST_GRAPHICS_API", cpp_namespace="rbc")
class TickStage(Enum):
    NONE = 0
    RasterPreview = 1
    PathTracingPreview = 2
    OffineCapturing = 3
    PresentOfflineResult = 4


@reflect(pybind=True, cpp_prefix="TEST_GRAPHICS_API", cpp_namespace="rbc")
class BuiltinKernels:
    def buffer_to_image(
        input_buffer: LCPYBufferInfo,
        output_image: LCPYImage2DInfo,
        pixel_offset: uint2,
        pixel_size: uint2,
        swizzle: uint4,
    ) -> None: ...

    def image_to_buffer(
        input_image: LCPYImage2DInfo,
        output_buffer: LCPYBufferInfo,
        pixel_offset: uint2,
        pixel_size: uint2,
        swizzle: uint4,
    ) -> None: ...


@reflect(pybind=True, cpp_prefix="TEST_GRAPHICS_API", cpp_namespace="rbc")
class SelectQuery:
    def valid() -> bool: ...
    def get_component() -> RenderComponent: ...
    def get_material() -> MaterialResource: ...
    def barycentric() -> float2: ...
    def get_submesh_index() -> uint: ...
    def prim_id() -> uint: ...


@reflect(pybind=True, cpp_prefix="TEST_GRAPHICS_API", cpp_namespace="rbc")
class RBCContext:
    def init_world(self, meta_path: str, binary_path: str) -> None: ...

    # frame

    def init_device(
        self, rhi_backend: str, program_path: str, shader_path: str, compactible: bool
    ) -> None: ...

    # render
    def init_render(self) -> None: ...

    def init_display(
        self,
        name: str,
        size: uint2,
        create_window: bool,
        window_resizable: bool,
        full_screen: bool,
        transparent: bool,
    ) -> None: ...

    def create_display_cam() -> CameraComponent: ...
    def destroy_display_cam() -> None: ...
    # view
    def reset_view(self, resolution: uint2) -> None: ...

    def disable_view(self) -> None: ...

    def tick(
        self,
        delta_time: float,  # for camera control
        tick_stage: TickStage,
        prepare_denoise: bool,
    ) -> bool: ...  # return: new input aquired

    def denoise(self) -> None: ...
    def save_display_image_to(self, path: str) -> None: ...
    def should_close(self) -> bool: ...
    def display_image(self) -> LCPYImage2D: ...

    def enable_camera_control() -> None: ...
    def disable_camera_control() -> None: ...
    def control_camera_add_pos(pos: float3) -> None: ...
    def control_camera_add_rotate(yaw: float, pitch: float, roll: float) -> None: ...
    # Upload host-data to device, resources must be installed
    def upload_texture_data(tex: TextureResource) -> None: ...
    def upload_mesh_data(mesh: MeshResource) -> None: ...
    def update_skinning_mesh(
        skinning_mesh: MeshResource, dual_quaternion_buffer: LCPYBufferInfo
    ) -> None: ...

    # callback
    def regist_callback(name: str, callback: Callback) -> None: ...
    def unregist_callback(name: str) -> None: ...

    # editing (no results in offline-rendering mode), can be used in headless mode with renderer
    def editing_add_click_requires(name: str, uv: float2) -> None: ...
    def editing_query_click_requires(name: str) -> SelectQuery: ...


OUT_CLASSES = [
    BasicDataType,
    ResourceLoadStatus,
    RendererGeometryType,
    BaseObjectType,
    Object,
    Entity,
    Component,
    TransformComponent,
    LightComponent,
    Resource,
    BasicData,
    TextureResource,
    MeshResource,
    BufferResource,
    MaterialResource,
    # GaussianSplatResource,
    VoxelResource,
    SDFVoxelResource,
    RenderComponent,
    RenderSettings,
    CameraComponent,
    DataComponent,
    DataComponentEventType,
    EntitiesCollection,
    Scene,
    FileMeta,
    Project,
    TickStage,
    SelectQuery,
    RBCContext,
    BuiltinKernels,
    SkeletonResource,
    SkinResource,
    AnimSequence,
    AnimSequenceResource,
    AnimGraphResource,
    SkelMeshResource,
    SkelMeshComponent,
    AtmosphereComponent,
]

__all__ = ["OUT_CLASSES"]
