[project]
dependencies = [
  "requests",
  "fastapi>=0.104.0",
  "uvicorn[standard]>=0.24.0",
  "pydantic>=2.0.0",
  "numpy>=2.3.5",
  "pillow>=12.1.1",
  "comfyui>=0.19.1",
]
description = "Make Robotics Cute!"
license = {file = "Licenses/Apache-2.0.txt"}
name = "robocute"
readme = "README.md"
requires-python = ">=3.14.3"
version = "0.2.4"

[tool.uv.sources]
comfyui = { git = "https://github.com/RoboCute/ComfyUI.git", branch = "rbc_thirdparty" }

[[tool.uv.index]]
default = true
url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[project.optional-dependencies]
dev = [
  "pytest>=9.0.1",
  "mypy>=1.19.0",
  "pybind11-stubgen>=2.5.5",
  "Pillow>=10.0.0",
]
publish = [
  "mkdocs>=1.6.1",
  "mkdocs-material>=9.0.0",
  "pymdown-extensions>=10.0.0",
  "mkdocs-i18n",
]

[project.scripts]
gen = "rbc_build.main:generate"
pre-pack = "rbc_build.main:pre_pack"
prepare = "rbc_build.main:prepare"

[build-system]
build-backend = "uv_build"
requires = ["uv_build>=0.11.7"]

[tool.uv.build-backend]
module-name = "robocute"
module-root = "src"
source-exclude = ["src/rbc_build/*", "src/rbc_meta/*"]

[tool.pytest.ini_options]
testpaths = [
  "test",
]
