from pathlib import Path

GENERATION_TASKS = [
    (
        "rbc_meta.test_codegen",
        "codegen_module",
        Path("rbc/tests/test_py_codegen/generated").resolve(),
        Path("src/rbc_ext/generated").resolve(),
    ),
    (
        "rbc_meta.test_serde",
        "codegen_header",
        Path("rbc/tests/test_serde/generated/generated.hpp").resolve(),
    ),
    (
        "rbc_meta.test_shared_window",
        "codegen_header",
        Path("rbc/tests/test_graphics/generated").resolve(),
        Path("rbc/tests/test_window_hook/generated").resolve(),
    ),
    (
        "rbc_meta.pipeline_settings",
        "codegen_header",
        Path(
            "rbc/render_plugin/include/rbc_render/generated/pipeline_settings.hpp"
        ).resolve(),
        Path("rbc/render_plugin/src/generated/pipeline_settings.cpp").resolve(),
    ),
    (
        "rbc_meta.resource_meta",
        "codegen_header",
        Path("rbc/runtime/include/rbc_runtime/generated/resource_meta.hpp").resolve(),
        Path("rbc/runtime/src/runtime/generated/resource_meta.cpp").resolve(),
    ),
    (
        "rbc_meta.resource_type",
        "codegen_header",
        Path("rbc/world/include/rbc_world/generated/resource_type.hpp").resolve(),
        Path("rbc/world/src/generated/resource_type.cpp").resolve(),
    ),
]
