#include "test_connection_view_runner.h"
#include <QDir>

ConnectionViewTestSetup::ConnectionViewTestSetup() {
    // Create mock service
    mockService_ = new MockConnectionService(this);
    
    // Create ViewModel
    viewModel_ = new ConnectionViewModel(mockService_, this);
    
    // Register QML types
    qmlRegisterType<ConnectionViewModel>("RoboCute.Connection", 1, 0, "ConnectionViewModel");
}

QObject *ConnectionViewTestSetup::mockViewModelProvider(QQmlEngine *engine, QJSEngine *scriptEngine) {
    Q_UNUSED(engine)
    Q_UNUSED(scriptEngine)
    
    // Return singleton instance
    static ConnectionViewTestSetup *instance = nullptr;
    if (!instance) {
        instance = new ConnectionViewTestSetup();
    }
    return instance->viewModel_;
}

// Main function for Qt Quick Test
// Qt Quick Test will automatically find test_connection_view.qml from qrc resources
QUICK_TEST_MAIN_WITH_SETUP(test_connection_view, ConnectionViewTestSetup)

// Note: MOC file for ConnectionViewTestSetup is automatically generated by xmake
// since the Q_OBJECT class is defined in the header file (test_connection_view_runner.h)
