#pragma once
#include <luisa/core/dll_export.h>

#ifdef RBC_CORE_EXPORT_DLL
#define RBC_CORE_API LUISA_DECLSPEC_DLL_EXPORT
#else
#define RBC_CORE_API LUISA_DECLSPEC_DLL_IMPORT
#endif

#ifdef RBC_RUNTIME_EXPORT_DLL
#define RBC_RUNTIME_API LUISA_DECLSPEC_DLL_EXPORT
#else
#define RBC_RUNTIME_API LUISA_DECLSPEC_DLL_IMPORT
#endif

#ifdef RBC_WORLD_EXPORT_DLL
#define RBC_WORLD_API LUISA_DECLSPEC_DLL_EXPORT
#else
#define RBC_WORLD_API LUISA_DECLSPEC_DLL_IMPORT
#endif

#ifdef RBC_IPC_EXPORT_DLL
#define RBC_IPC_API LUISA_DECLSPEC_DLL_EXPORT
#else
#define RBC_IPC_API LUISA_DECLSPEC_DLL_IMPORT
#endif
