#pragma once

#include <QWidget>
#include <QListWidget>
#include <QVBoxLayout>
#include <QLabel>

namespace rbc {

class SceneSync;

/**
 * Result Panel Widget
 * 
 * Displays execution results including animations generated by nodes.
 * Shows list of animations with metadata and allows selection for playback.
 */
class ResultPanel : public QWidget {
    Q_OBJECT

public:
    explicit ResultPanel(QWidget *parent = nullptr);
    
    // Update from scene sync (called when animations change)
    void updateFromSync(const SceneSync *sync);
    
    // Clear all results
    void clear();

signals:
    // Emitted when an animation is selected
    void animationSelected(QString animName);

private slots:
    void onAnimationItemClicked(QListWidgetItem *item);

private:
    QListWidget *animationList_;
    QLabel *titleLabel_;
    QLabel *statusLabel_;
    
    void setupUi();
};

}  // namespace rbc

